### ISSUE TITLE
Usage in clustered environment

### ISSUE THREAD

**Issue by gitkeerthi** [reugn/go-quartz#45]
How do you use this in a clustered environment where more than one instance of the scheduler might exist? Is there a feature similar to quartz cluster mode (https://flylib.com/books/en/2.65.1/how_clustering_works_in_quartz.html)?

**Comment by reugn** [comment]
@gitkeerthi Clustering is not supported within the library, but a persistent job store can be implemented independently.

**Comment by gedw99** [comment]
Maybe a simple global system like etcd , kine or nats would be a simple global locking store .

let’s use NATS because it has subscriptions which is handy.

When a job starts it registers with NATS . 

So on job start , check with NATS and if not in nats, run the job.

On job finish , unregister with nats

—-

you can embed nats servers in your project too which is handy . Nats will automatically do leader election so if a server fails and new leader is automatically chosen .
It also has gracefull upgrades using lamb duck mode. So this means you don’t have to run a “special jobs locking server” but can just include it in your golang project

**Comment by bingtianyiyan** [comment]
please have planing for support cluster

**Comment by joint-song** [comment]
You mean that we can create multiple instances of `Scheduler`, and these schedulers can have respective Persistent Queue(We can surely set a field in RDBMS table to seperate each queue jobs)? Each scheduler has own timer, event-loop etc. Please correct me if I misunderstand this solution.

**Comment by reugn** [comment]
By implementing a shared persistence layer, you can enable multiple scheduler instances to retrieve and process jobs. This architecture supports high availability (HA) scenarios and facilitates scalability when job processing becomes highly competitive.
